### ISSUE TITLE
Autocomplete bug

### ISSUE THREAD

**Issue by simonlindholm** [HalfVoxel/codenames-android#18]
Sometimes taking a photo results in autocomplete for the last entry showing up at the first input?

I'd actually suggest that the first input doesn't even get focus, since everything is already filled in. But it should probably have focus at the very beginning, just to show that one can use the input fields.

(BTW, can one move the autocomplete suggestions into the keyboard, like how regular autocompletion is done in Android?)

**Comment by Gullesnuffs** [comment]
I'm pretty sure it's impossible to move the suggestion into the keyboard.

**Comment by simonlindholm** [comment]
763f40e7a7a2026363ade44890261226011542d3
